load('dat.RData')
Sys.setlocale("LC_TIME", "English")
png("plot3.png")
with(dat, {
  plot(Time, Sub_metering_1, yaxt = 'n', type = 'l',xlab = '',ylab = 'Energy sub metering')
  axis(side=2, at=seq(0, 40, by=10))
  lines(Time,Sub_metering_2,col= 'red')
  lines(Time, Sub_metering_3, col = 'blue')
  legend('topright', legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'), col = c('black','red','blue'),lty = 1)
})
dev.off()
